/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cari;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import tampilan.kamar;
import tampilan.rekammedis;

/**
 *
 * @author Asus
 */
public class cariRekam extends javax.swing.JFrame {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public kamar kamar = null;

    /**
     * Creates new form cariRema
     */
    public cariRekam() {
        initComponents();
        datatable();
    }

    protected void datatable() {
        Object[] Baris = {"ID Periksa", "Nama Dokter", "Nama Pasien", "Tanggal", "Diagnosis", "Gejala"};
        tabmode = new DefaultTableModel(null, Baris);
        tablerekam.setModel(tabmode);

        String sql = "SELECT rekam_medis.id_rekammedis, dokter.nama_dokter, pasien.nama_pasien, rekam_medis.tanggal_periksa, rekam_medis.gejala, rekam_medis.diagnosis "
                + "FROM rekam_medis "
                + "JOIN dokter ON rekam_medis.id_dokter = dokter.id_dokter "
                + "JOIN pasien ON rekam_medis.id_pasien = pasien.id_pasien";

        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("id_rekammedis");
                String b = hasil.getString("nama_pasien");
                String c = hasil.getString("nama_dokter");
                String d = hasil.getString("tanggal_periksa");
                String e = hasil.getString("diagnosis");
                String f = hasil.getString("gejala");

                String[] data = {a, b, c, d, e, f};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablerekam = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablerekam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablerekam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablerekamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablerekam);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablerekamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablerekamMouseClicked
        int selectedRow = tablerekam.rowAtPoint(evt.getPoint());
        if (selectedRow >= 0) {
            kamar.namaPas = tablerekam.getValueAt(selectedRow, 1).toString();
            kamar.namaDok = tablerekam.getValueAt(selectedRow, 2).toString();
            kamar.diagnosis = tablerekam.getValueAt(selectedRow, 4).toString();

            try {
                String dateStr = tablerekam.getValueAt(selectedRow, 3).toString();
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateStr);
                kamar.tgl = date;
            } catch (ParseException e) {
                e.printStackTrace();
            }
            kamar.rekamTerpilih();
            this.dispose();
        }
    }//GEN-LAST:event_tablerekamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cariRekam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cariRekam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cariRekam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cariRekam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cariRekam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablerekam;
    // End of variables declaration//GEN-END:variables
}
