/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cari;

import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import tampilan.kamar;
import tampilan.pembayaran;

/**
 *
 * @author Asus
 */
public class cariBayar extends javax.swing.JFrame {

    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public pembayaran bayar = null;

    /**
     * Creates new form cariBayar
     */
    public cariBayar() {
        initComponents();
        datatable();
    }

    protected void datatable() {
        Object[] Baris = {"ID Rekam Medis", "Nama Pasien", "Diagnosis", "Tanggal Masuk", "Nama Kamar", "Nama Dokter", "Nama Obat", "Harga Kamar", "Harga Obat"};
        tabmode = new DefaultTableModel(null, Baris);
        tablebayar.setModel(tabmode);

        // SQL query to join rekam_medis with dokter, pasien, obat, and kamar
        String sql = "SELECT rm.id_rekammedis, ps.nama_pasien, rm.diagnosis, rm.tanggal_periksa, km.nama_kamar, dk.nama_dokter, ob.nama_obat, km.harga AS harga_kamar, ob.harga AS harga_obat "
                   + "FROM rekam_medis rm "
                   + "INNER JOIN dokter dk ON rm.id_dokter = dk.id_dokter "
                   + "INNER JOIN pasien ps ON rm.id_pasien = ps.id_pasien "
                   + "INNER JOIN kamar km ON rm.id_kamar = km.id_kamar "
                   + "INNER JOIN obat ob ON rm.id_obat = ob.id_obat";

        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("id_rekammedis");
                String b = hasil.getString("nama_pasien");
                String c = hasil.getString("diagnosis");
                String d = hasil.getString("tanggal_periksa");
                String e = hasil.getString("nama_kamar");
                String f = hasil.getString("nama_dokter");
                String g = hasil.getString("nama_obat");
                String h = hasil.getString("harga_kamar");
                String i = hasil.getString("harga_obat");

                String[] data = {a, b, c, d, e, f, g, h, i};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablebayar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablebayar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablebayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebayarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablebayar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablebayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebayarMouseClicked
        // TODO add your handling code here:
        int selectedRow = tablebayar.rowAtPoint(evt.getPoint());
        if (selectedRow >= 0) {
            // Sesuaikan dengan indeks yang benar berdasarkan urutan kolom di 'datatable'
            bayar.namaPas = tablebayar.getValueAt(selectedRow, 1).toString(); 
            bayar.diagnosis = tablebayar.getValueAt(selectedRow, 2).toString();

            try {
                // Tanggal periksa dari kolom yang sesuai
                String dateStr = tablebayar.getValueAt(selectedRow, 3).toString();
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateStr);
                bayar.tanggalmasuk = date;
            } catch (ParseException e) {
                e.printStackTrace();
            }
            bayar.namaKamar = tablebayar.getValueAt(selectedRow, 4).toString(); 
            bayar.namaDok = tablebayar.getValueAt(selectedRow, 5).toString(); 
            bayar.namaObat = tablebayar.getValueAt(selectedRow, 6).toString(); 
            bayar.hargaKamar = tablebayar.getValueAt(selectedRow, 7).toString(); 
            bayar.hargaObat = tablebayar.getValueAt(selectedRow, 8).toString(); 
            bayar.bayarTerpilih();
            this.dispose(); // Menutup jendela saat operasi selesai
        }
    }//GEN-LAST:event_tablebayarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cariBayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cariBayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cariBayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cariBayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cariBayar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablebayar;
    // End of variables declaration//GEN-END:variables
}
