/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Asus
 */
public class dokter extends javax.swing.JFrame {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form dokter
     */
    public dokter() {
        initComponents();
        datatable();
    }

    protected void kosong() {
        tnama.setText("");
        tspesialis.setText("");
        thp.setText("");
        temail.setText("");
        talamat.setText("");
    }

    protected void datatable() {
        Object[] Baris = {"ID Dokter", "Nama Dokter", "Spesialis", "No HP/Telepon", "Email", "Alamat"};
        tabmode = new DefaultTableModel(null, Baris);
        tabledokter.setModel(tabmode);
        String sql = "SELECT * FROM dokter";

        try (Statement stat = conn.createStatement(); ResultSet hasil = stat.executeQuery(sql)) {
            while (hasil.next()) {
                String id = hasil.getString("id_dokter"); // Menambahkan pengambilan ID
                String nama = hasil.getString("nama_dokter");
                String spesialis = hasil.getString("spesialis");
                String noHp = hasil.getString("nohp");
                String email = hasil.getString("email");
                String alamat = hasil.getString("alamat");

                String[] data = {id, nama, spesialis, noHp, email, alamat}; // Menambahkan ID ke dalam data yang ditampilkan
                tabmode.addRow(data);

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Kesalahan saat mengambil data: " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        thp = new javax.swing.JTextField();
        bsimpan = new javax.swing.JButton();
        bkembali = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        temail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        talamat = new javax.swing.JTextField();
        bperbarui = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledokter = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tiddokter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tspesialis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dokter");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Nama Dokter");

        jLabel4.setText("Email");

        jLabel5.setText("Telp/HP");

        thp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thpActionPerformed(evt);
            }
        });

        bsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/save.png"))); // NOI18N
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        bkembali.setText("Kembali");
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });

        bhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete.png"))); // NOI18N
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        jLabel6.setText("Alamat");

        bperbarui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/update.png"))); // NOI18N
        bperbarui.setText("Perbarui");
        bperbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bperbaruiActionPerformed(evt);
            }
        });

        tabledokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabledokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledokterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledokter);

        jLabel7.setText("Id Dokter");

        jLabel1.setText("Spesialis");

        tspesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tspesialisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(280, Short.MAX_VALUE)
                        .addComponent(bsimpan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tiddokter, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addComponent(tnama, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(tspesialis, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bperbarui)
                        .addGap(31, 31, 31)
                        .addComponent(bhapus)
                        .addGap(18, 18, 18)
                        .addComponent(bkembali))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thp, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(talamat)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tiddokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(talamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(thp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bkembali)
                            .addComponent(bhapus)
                            .addComponent(bperbarui)
                            .addComponent(bsimpan)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tspesialis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_bkembaliActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        String iddokter = tiddokter.getText();
        String namadokter = tnama.getText();
        String spesialis = tspesialis.getText();
        String notelp = thp.getText();
        String email = temail.getText();
        String alamat = talamat.getText();
        
        if (conn != null) {
            try {
                String query = "UPDATE dokter SET nama_dokter = ?, spesialis = ?, nohp = ?, email = ?, alamat = ? WHERE id_dokter = ?";
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setString(1, namadokter);
                stmt.setString(2, spesialis);
                stmt.setString(3, notelp);
                stmt.setString(4, email);
                stmt.setString(5, alamat);
                stmt.setString(6, iddokter);

                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Dokter berhasil diupdate");
                kosong();
                datatable();

                stmt.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Kesalahan database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Koneksi database belum diinisialisasi.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:\
        String iddokter = tiddokter.getText();

        if (conn != null) {
            try {
                String query = "DELETE FROM dokter WHERE id_dokter = ?";
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setString(1, iddokter);

                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Dokter berhasil dihapus");
                kosong();
                datatable();

                stmt.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Kesalahan database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Koneksi database belum diinisialisasi.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bperbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bperbaruiActionPerformed
        try {
            int selectedRow = tabledokter.getSelectedRow(); // Mengambil baris yang dipilih
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Pilih baris yang akan diperbarui");
                return;
            }

            String id = tabledokter.getValueAt(selectedRow, 0).toString(); // Mengambil id dari baris yang dipilih

            String sql = "UPDATE dokter SET nama_dokter=?, spesialis = ?, nohp=?, email=?, alamat=? WHERE id_dokter=?";
            PreparedStatement stat = conn.prepareStatement(sql);

            stat.setString(1, tnama.getText());
            stat.setString(2, tspesialis.getText());
            stat.setString(3, thp.getText());
            stat.setString(4, temail.getText());
            stat.setString(5, talamat.getText());
            stat.setString(6, id); // ID diambil dari tabel

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui");
            datatable(); // Memuat ulang data ke tabel
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memperbarui data: " + e.getMessage());
        }
    }//GEN-LAST:event_bperbaruiActionPerformed

    private void tabledokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledokterMouseClicked
        // TODO add your handling code here:
        int Bar = tabledokter.getSelectedRow();

        String id = tabmode.getValueAt(Bar, 0).toString();
        String nama = tabmode.getValueAt(Bar, 1).toString();
        String spesialis = tabmode.getValueAt(Bar, 2).toString();
        String noHp = tabmode.getValueAt(Bar, 3).toString();
        String email = tabmode.getValueAt(Bar, 4).toString();
        String alamat = tabmode.getValueAt(Bar, 5).toString();

        tnama.setText(nama);
        tspesialis.setText(spesialis);
        thp.setText(noHp);
        temail.setText(email);
        talamat.setText(alamat);
    }//GEN-LAST:event_tabledokterMouseClicked

    private void tspesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tspesialisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tspesialisActionPerformed

    private void thpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkembali;
    private javax.swing.JButton bperbarui;
    private javax.swing.JButton bsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabledokter;
    private javax.swing.JTextField talamat;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField thp;
    private javax.swing.JTextField tiddokter;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tspesialis;
    // End of variables declaration//GEN-END:variables
}
