/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import cari.cariDokter;
import cari.cariPasien;
import cari.cariRekam;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Asus
 */
public class kamar extends javax.swing.JFrame {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public String namaDok, namaPas, diagnosis;
    public java.util.Date tgl;

    public String getNamaDok() {
        return namaDok;
    }

    public String getNamaPas() {
        return namaPas;
    }

    public java.util.Date gettanggal() {
        return tgl;
    }

    public String getDiagnosis() {
        return diagnosis;
    }

    /**
     * Creates new form kamar
     */
    public kamar() {
        initComponents();
        datatable();
    }

    protected void datatable() {
        Object[] Baris = {"Id Kamar", "Nama Pasien", "Diagnosis", "Nama Kamar", "Nama Dokter", "Harga", "Tanggal Masuk"};
        tabmode = new DefaultTableModel(null, Baris);
        tablekamar.setModel(tabmode);

        String sql = "SELECT kamar.id_kamar, pasien.nama_pasien, rekam_medis.diagnosis, kamar.nama_kamar, dokter.nama_dokter, kamar.harga,kamar.tanggal "
                + "FROM rekam_medis "
                + "JOIN kamar ON rekam_medis.id_rekammedis = kamar.id_kamar "
                + "JOIN pasien ON rekam_medis.id_pasien = pasien.id_pasien "
                + "JOIN dokter ON rekam_medis.id_dokter = dokter.id_dokter";

        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("id_kamar");
                String b = hasil.getString("nama_pasien");
                String c = hasil.getString("diagnosis");
                String d = hasil.getString("nama_kamar");
                String e = hasil.getString("nama_dokter");
                String f = hasil.getString("harga");
                String g = hasil.getString("tanggal");

                String[] data = {a, b, c, d, e, f, g};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void rekamTerpilih() {
        cariRekam cr = new cariRekam();
        cr.kamar = this;
        tnamapasien.setText(namaPas);
        tdiagnosis.setText(diagnosis);
        tnamadokter.setText(namaDok);
        tanggal.setDate(tgl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnamapasien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        tnamadokter = new javax.swing.JTextField();
        cbkamar = new javax.swing.JComboBox<>();
        tdiagnosis = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablekamar = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tidkamar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tharga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Pasien");

        jLabel3.setText("Diagnosa");

        jLabel4.setText("Kamar");

        jLabel5.setText("Nama Dokter");

        jLabel2.setText("Tanggal Masuk");

        cbkamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kamar VVIP", "Kamar Biasa", "Kamar Sitorus", "Kamar Wah Bange" }));
        cbkamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkamarActionPerformed(evt);
            }
        });

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/save.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        tablekamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablekamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablekamarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablekamar);

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-pencil-24.png"))); // NOI18N
        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        jLabel6.setText("Id Kamar");

        jLabel7.setText("Harga Kamar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbkamar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tdiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tidkamar, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tnamapasien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btncari))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnsimpan)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnubah))
                                            .addComponent(tnamadokter, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnhapus)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnkembali))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(tharga, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tidkamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tnamapasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tdiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbkamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tnamadokter, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnhapus)
                    .addComponent(btnubah)
                    .addComponent(btnkembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbkamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkamarActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        try {
            String idKamar = tidkamar.getText();
            String namaKamar = cbkamar.getSelectedItem().toString();
            String harga = tharga.getText();
            java.util.Date tanggalMasuk = tanggal.getDate();
            java.sql.Date sqlDate = new java.sql.Date(tanggalMasuk.getTime());

            String sql = "UPDATE kamar SET nama_kamar=?, harga=?,tanggal=? WHERE id_kamar=?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, namaKamar);
            pstmt.setString(2, harga);
            pstmt.setDate(3, sqlDate);
            pstmt.setString(4, idKamar);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            datatable(); // Refresh tabel
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void tablekamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablekamarMouseClicked
        // TODO add your handling code here:
        int row = tablekamar.getSelectedRow();
        String idKamar = tablekamar.getValueAt(row, 0).toString();
        String namaPasien = tablekamar.getValueAt(row, 1).toString();
        String diagnosis = tablekamar.getValueAt(row, 2).toString();
        String namaKamar = tablekamar.getValueAt(row, 3).toString();
        String namaDokter = tablekamar.getValueAt(row, 4).toString();
        String harga = tablekamar.getValueAt(row, 5).toString();
        String tanggalMasuk = tablekamar.getValueAt(row, 6).toString();

        tidkamar.setText(idKamar);
        tnamapasien.setText(namaPasien);
        tdiagnosis.setText(diagnosis);
        cbkamar.setSelectedItem(namaKamar);
        tnamadokter.setText(namaDokter);
        tharga.setText(harga);
        try {
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tanggalMasuk);
            tanggal.setDate(date);
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tablekamarMouseClicked

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        cariRekam cr = new cariRekam();
        cr.kamar = this;
        cr.setVisible(true);
        cr.setResizable(false);
//        tiddokter.setEnabled(false);
        tnamadokter.setEnabled(false);
    }//GEN-LAST:event_btncariActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:                               
        try {
            String idKamar = tidkamar.getText();
            String namaKamar = cbkamar.getSelectedItem().toString();
            String harga = tharga.getText();
            java.util.Date tanggalMasuk = tanggal.getDate();
            java.sql.Date sqlDate = new java.sql.Date(tanggalMasuk.getTime());

            String sql = "INSERT INTO kamar (id_kamar, nama_kamar, harga,tanggal) VALUES (?,?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, idKamar);
            pstmt.setString(2, namaKamar);
            pstmt.setString(3, harga);
            pstmt.setDate(4, sqlDate);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            datatable(); // Refresh tabel
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            String idKamar = tidkamar.getText();

            String sql = "DELETE FROM kamar WHERE id_kamar=?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, idKamar);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            datatable(); // Refresh tabel
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cbkamar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablekamar;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField tdiagnosis;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tidkamar;
    private javax.swing.JTextField tnamadokter;
    private javax.swing.JTextField tnamapasien;
    // End of variables declaration//GEN-END:variables
}
