/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Asus
 */
public class resep extends javax.swing.JFrame {
    
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    private dokter caridokter;
    private JTable tabledokter;
    private pasien caripasien;
    private JTable tablepasien;
    private obat cariobat;
    private JTable tableobat;

    /**
     * Creates new form resep
     */
    public resep() {
        initComponents();
        datatable();
        caridokter = new dokter();
        tabledokter = caridokter.getTableDokter();
        caripasien = new pasien();
        tablepasien = caripasien.getTablePasien();
        cariobat = new obat();
        tableobat = cariobat.getTableObat();
    }
    
    protected void kosong() {
        tkode_dokter.setText("");
        tnama_dokter.setText("");
        tgl.setDate(null);
        tkode_pasien.setText("");
        tnama_pasien.setText("");
        tkode_obat.setText("");
        tnama_obat.setText("");
    }
    
    protected void datatable() {
        Object[] Baris = {"Nama Pasien", "Nama Dokter", "Nama Obat", "Tanggal"};
        tabmode = new DefaultTableModel(null, Baris);
        tableresep.setModel(tabmode);
        String sql = "select * from resep";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("nama_pasien");
                String b = hasil.getString("nama_dokter");
                String c = hasil.getString("nama_obat");
                String d = hasil.getString("tanggal");
                
                String[] data = {a, b, c, d,};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tkode_pasien = new javax.swing.JTextField();
        tnama_pasien = new javax.swing.JTextField();
        tkode_dokter = new javax.swing.JTextField();
        tnama_obat = new javax.swing.JTextField();
        tnama_dokter = new javax.swing.JTextField();
        tkode_obat = new javax.swing.JTextField();
        tgl = new com.toedter.calendar.JDateChooser();
        bsimpan = new javax.swing.JButton();
        bperbarui = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bkembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableresep = new javax.swing.JTable();
        bcari_pasien = new javax.swing.JButton();
        bcari_dokter = new javax.swing.JButton();
        bcariobat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode Pasien");

        jLabel2.setText("Nama Pasien");

        jLabel3.setText("Kode Dokter");

        jLabel4.setText("Nama Dokter");

        jLabel5.setText("Detail Obat");

        jLabel6.setText("___________________________________________________");

        jLabel7.setText("Kode Obat");

        jLabel8.setText("Nama Obat");

        jLabel9.setText("Tanggal");

        bsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/save.png"))); // NOI18N
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bperbarui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/update.png"))); // NOI18N
        bperbarui.setText("Perbarui");
        bperbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bperbaruiActionPerformed(evt);
            }
        });

        bhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete.png"))); // NOI18N
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        bkembali.setText("kembali");
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });

        tableresep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableresep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableresepMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableresep);

        bcari_pasien.setText("...");
        bcari_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcari_pasienActionPerformed(evt);
            }
        });

        bcari_dokter.setText("...");
        bcari_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcari_dokterActionPerformed(evt);
            }
        });

        bcariobat.setText("....");
        bcariobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariobatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(bsimpan)
                        .addGap(20, 20, 20)
                        .addComponent(bperbarui)
                        .addGap(20, 20, 20)
                        .addComponent(bhapus)
                        .addGap(20, 20, 20)
                        .addComponent(bkembali))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tnama_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tkode_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(bcari_dokter))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tkode_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(bcari_pasien))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(tnama_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(23, 23, 23)
                                                .addComponent(tkode_obat, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bcariobat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(tnama_obat)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tkode_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcari_pasien)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tnama_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tkode_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcari_dokter))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tnama_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tkode_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcariobat))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tnama_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpan)
                    .addComponent(bperbarui)
                    .addComponent(bhapus)
                    .addComponent(bkembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcari_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcari_pasienActionPerformed
        // TODO add your handling code here:
        caripasien = new pasien();
        tablepasien = caripasien.getTablePasien();
        
        JScrollPane scrollPane = new JScrollPane(tablepasien);
        
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Cari Pasien", true);
        dialog.getContentPane().add(scrollPane);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        
        tablepasien.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = tablepasien.getSelectedRow();
                    if (selectedRow != -1) {
                        String kodeDokter = tablepasien.getValueAt(selectedRow, 0).toString();
                        String namaDokter = tablepasien.getValueAt(selectedRow, 1).toString();
                        tkode_pasien.setText(kodeDokter);
                        tnama_pasien.setText(namaDokter);
                        dialog.dispose();
                    }
                }
            }
        });
        
        dialog.setVisible(true);
    }//GEN-LAST:event_bcari_pasienActionPerformed

    private void bcari_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcari_dokterActionPerformed
        // TODO add your handling code here:
        caridokter = new dokter();
        tabledokter = caridokter.getTableDokter();
        
        JScrollPane scrollPane = new JScrollPane(tabledokter);
        
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Cari Dokter", true);
        dialog.getContentPane().add(scrollPane);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        
        tabledokter.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = tabledokter.getSelectedRow();
                    if (selectedRow != -1) {
                        String kodeDokter = tabledokter.getValueAt(selectedRow, 0).toString();
                        String namaDokter = tabledokter.getValueAt(selectedRow, 1).toString();
                        tkode_dokter.setText(kodeDokter);
                        tnama_dokter.setText(namaDokter);
                        dialog.dispose();
                    }
                }
            }
        });
        
        dialog.setVisible(true);
    }//GEN-LAST:event_bcari_dokterActionPerformed

    private void bcariobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariobatActionPerformed
        // TODO add your handling code here:
        cariobat = new obat();
        tableobat = cariobat.getTableObat();
        
        JScrollPane scrollPane = new JScrollPane(tableobat);
        
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Cari Obat", true);
        dialog.getContentPane().add(scrollPane);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        
        tableobat.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = tableobat.getSelectedRow();
                    if (selectedRow != -1) {
                        String kodeDokter = tableobat.getValueAt(selectedRow, 0).toString();
                        String namaDokter = tableobat.getValueAt(selectedRow, 1).toString();
                        tkode_obat.setText(kodeDokter);
                        tnama_obat.setText(namaDokter);
                        dialog.dispose();
                    }
                }
            }
        });
        
        dialog.setVisible(true);
    }//GEN-LAST:event_bcariobatActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        String iddokter = tkode_dokter.getText();
        String namadokter = tnama_dokter.getText();
        java.util.Date date = tgl.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(date);
        String idpasien = tkode_pasien.getText();
        String namapasien = tnama_pasien.getText();
        String idobat = tkode_obat.getText();
        String namaobat = tnama_obat.getText();
        
        try {
            String query = "INSERT INTO resep (kode_pasien, nama_pasien, kode_dokter, nama_dokter, kode_obat, nama_obat, tanggal) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, idpasien);
            stmt.setString(2, namapasien);
            stmt.setString(3, iddokter);
            stmt.setString(4, namadokter);
            stmt.setString(5, idobat);
            stmt.setString(6, namaobat);
            stmt.setString(7, tanggal);
            
            
            stmt.executeUpdate();
            kosong();
            datatable();
            JOptionPane.showMessageDialog(this, "Data Pemeriksaan berhasil disimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bperbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bperbaruiActionPerformed
        // TODO add your handling code here:
        String iddokter = tkode_dokter.getText();
        String namadokter = tnama_dokter.getText();
        java.util.Date date = tgl.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(date);
        String idpasien = tkode_pasien.getText();
        String namapasien = tnama_pasien.getText();
        String idobat = tkode_obat.getText();
        String namaobat = tnama_obat.getText();
        
        try {
            String query = "UPDATE resep SET nama_pasien=?, kode_dokter=?, nama_dokter=?, kode_obat=?, nama_obat=?, tanggal=? WHERE kode_pasien=?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, namapasien);
            stmt.setString(2, iddokter);
            stmt.setString(3, namadokter);
            stmt.setString(4, idobat);
            stmt.setString(5, namaobat);
            stmt.setString(6, tanggal);
            stmt.setString(7, idpasien);
            
            int rowsAffected = stmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Data Resep berhasil diperbarui");
                kosong();
                datatable();
            } else {
                JOptionPane.showMessageDialog(this, "Tidak ada data dengan kode pasien " + idpasien, "Error", JOptionPane.ERROR_MESSAGE);
            }
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bperbaruiActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        String idpasien = tkode_pasien.getText();
        
        try {
            String query = "DELETE FROM resep WHERE kode_pasien=?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, idpasien);
            
            int rowsAffected = stmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Data Resep berhasil dihapus");
                kosong();
                datatable();
            } else {
                JOptionPane.showMessageDialog(this, "Tidak ada data dengan kode pasien " + idpasien, "Error", JOptionPane.ERROR_MESSAGE);
            }
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_bkembaliActionPerformed

    private void tableresepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableresepMouseClicked
        // TODO add your handling code here:
        int Bar = tableresep.getSelectedRow();
        String a = tabmode.getValueAt(Bar, 0).toString();
        String b = tabmode.getValueAt(Bar, 1).toString();
        String c = tabmode.getValueAt(Bar, 2).toString();
        String d = tabmode.getValueAt(Bar, 3).toString();
   
        tnama_pasien.setText(a);
        tnama_dokter.setText(b);
        tnama_obat.setText(c);
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date tanggal = sdf.parse(d);
            tgl.setDate(tanggal);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Format tanggal salah: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tgl.setDate(null);
        }
    }//GEN-LAST:event_tableresepMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari_dokter;
    private javax.swing.JButton bcari_pasien;
    private javax.swing.JButton bcariobat;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkembali;
    private javax.swing.JButton bperbarui;
    private javax.swing.JButton bsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableresep;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JTextField tkode_dokter;
    private javax.swing.JTextField tkode_obat;
    private javax.swing.JTextField tkode_pasien;
    private javax.swing.JTextField tnama_dokter;
    private javax.swing.JTextField tnama_obat;
    private javax.swing.JTextField tnama_pasien;
    // End of variables declaration//GEN-END:variables
}
